export const routes = {
    login: '/login',
    overview: '/',
    events: '/events',
    alerts: '/alerts',
    incidents: '/incidents',
    evidence: '/evidence',
    risk: '/risk',
    'attack-graph': '/attack-graph',
    heatmap: '/heatmap',
    'user-risk': '/user-risk',
    policies: '/policies',
    'policy-editor': '/policies/:id/edit',
    'policy-diff': '/policies/:id/diff',
    configuration: '/configuration',
    explainability: '/explainability',
    'break-glass': '/admin/break-glass',
    'high-risk-actions': '/admin/high-risk-actions',
    sla: '/sla',
}
