import React, { useEffect, useState } from "react";

type Scenario = { id: string; label: string; description: string; decision: string; reason: string; rule: string; latency: string; tone: "safe" | "blocked" | "challenge"; request: string };
const SCENARIOS: Scenario[] = [
  { id: "safe-api", label: "Low-risk API request", description: "A normal request that stays within the configured baseline.", decision: "Allowed", reason: "No WAF violation and behavior remains within baseline.", rule: "Baseline policy", latency: "18ms", tone: "safe", request: "GET /api/v1/profile" },
  { id: "sqli-json", label: "SQL injection in JSON", description: "A controlled fixture containing a known SQL injection pattern.", decision: "Blocked", reason: "OWASP CRS SQL injection rule matched; upstream was not reached.", rule: "CRS SQLi detection", latency: "7ms", tone: "blocked", request: "POST /api/search · controlled JSON fixture" },
  { id: "credential-burst", label: "Credential stuffing burst", description: "A fixed burst pattern that exceeds the authentication baseline.", decision: "Challenged", reason: "Behavior signal exceeded the configured authentication threshold.", rule: "Behavior threshold", latency: "11ms", tone: "challenge", request: "POST /auth/login · controlled burst" },
];
const PIPELINE = ["Incoming request", "WAF & rate limit", "Behavior & risk", "Decision", "Upstream"];

export default function DemoPage() {
  const [selectedId, setSelectedId] = useState(SCENARIOS[0].id);
  const [running, setRunning] = useState(false);
  const [stage, setStage] = useState(-1);
  const scenario = SCENARIOS.find((item) => item.id === selectedId) || SCENARIOS[0];
  useEffect(() => { if (!running) return; setStage(-1); const timers = PIPELINE.map((_, index) => window.setTimeout(() => setStage(index), (index + 1) * 420)); const done = window.setTimeout(() => setRunning(false), (PIPELINE.length + 1) * 420); return () => { timers.forEach(window.clearTimeout); window.clearTimeout(done); }; }, [running, selectedId]);
  return <div className="demo-page"><header className="demo-nav"><a className="demo-brand" href="/login"><span className="brand-mark">SL</span><span><b>SentinelLayer</b><small>Security control plane</small></span></a><div className="demo-nav-actions"><span className="demo-label">Controlled simulation</span><a className="secondary-button compact-button" href="/login">Open console</a></div></header><main className="demo-main"><section className="demo-hero"><p className="eyebrow">INTERACTIVE PROTECTION DEMO</p><h1>See how SentinelLayer makes a security decision.</h1><p>Choose a fixed test scenario and watch it move through the protection pipeline. This demo uses controlled fixtures only—it is not customer traffic and does not accept arbitrary targets.</p></section><section className="demo-layout"><aside className="demo-scenarios"><div className="panel-heading"><div><p className="eyebrow">TEST SCENARIOS</p><h2>Choose a request</h2></div></div>{SCENARIOS.map((item) => <button key={item.id} className={`scenario-button ${selectedId === item.id ? "scenario-button-active" : ""}`} type="button" onClick={() => { setSelectedId(item.id); setRunning(false); }}><span className={`scenario-icon scenario-icon-${item.tone}`}>{item.tone === "blocked" ? "!" : item.tone === "challenge" ? "?" : "•"}</span><span><b>{item.label}</b><small>{item.description}</small></span></button>)}</aside><section className="demo-stage"><div className="demo-request"><div><p className="eyebrow">CONTROLLED REQUEST</p><h2>{scenario.request}</h2><p>{scenario.description}</p></div><button className="primary-button compact-button" type="button" onClick={() => setRunning(true)} disabled={running}>{running ? "Evaluating…" : "Run scenario"}</button></div><div className="demo-pipeline">{PIPELINE.map((step, index) => <React.Fragment key={step}><div className={`demo-pipeline-step ${stage >= index ? "demo-pipeline-step-active" : ""}`}><span>{String(index + 1).padStart(2, "0")}</span><b>{step}</b></div>{index < PIPELINE.length - 1 && <div className={`demo-pipeline-line ${stage > index ? "demo-pipeline-line-active" : ""}`} />}</React.Fragment>)}</div><div className={`demo-decision demo-decision-${scenario.tone}`}><div className="decision-icon">{scenario.tone === "blocked" ? "!" : scenario.tone === "challenge" ? "?" : "✓"}</div><div><p className="eyebrow">SENTINELLAYER DECISION</p><h2>{scenario.decision}</h2><p>{scenario.reason}</p></div><div className="demo-meta"><span><small>Matched rule</small><b>{scenario.rule}</b></span><span><small>Pipeline latency</small><b>{scenario.latency}</b></span></div></div><div className="demo-footnote"><strong>What this proves</strong><span>The production Gateway uses the same decision stages, while this page remains isolated to fixed, safe demonstration fixtures.</span></div></section></section></main></div>;
}
