import React, { useEffect, useMemo, useState } from "react";
import { apiGet, apiPost, ApiError } from "../../api/client";

type Alert = { id: string; severity: string; message: string; source?: string; status: string; created_at?: string; resolved_at?: string | null; resolved_by?: string | null };
function errorMessage(error: unknown): string { return (error as ApiError)?.message || (error instanceof Error ? error.message : "Unable to load alerts"); }
function formatDate(value?: string | null): string { if (!value) return "Time unavailable"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "Time unavailable" : date.toLocaleString(); }

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [filter, setFilter] = useState("active");
  const [loading, setLoading] = useState(true);
  const [resolving, setResolving] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); try { const path = filter === "all" ? "/alerts" : `/alerts?status=${encodeURIComponent(filter)}`; const data = await apiGet<Alert[]>(path); setAlerts(Array.isArray(data) ? data : []); setError(null); } catch (currentError) { setError(errorMessage(currentError)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [filter]);
  async function resolve(id: string) { setResolving(id); setError(null); try { await apiPost(`/alerts/${id}/resolve`, {}); await load(); } catch (currentError) { setError(errorMessage(currentError)); } finally { setResolving(null); } }
  const critical = useMemo(() => alerts.filter((item) => /critical|high/i.test(item.severity)).length, [alerts]);
  return <div className="page"><section className="hero-row"><div><p className="eyebrow">DETECT / RESPONSE</p><h1 className="page-title">Alerts</h1><p className="page-lede">Prioritize active signals, understand their source, and resolve only after the response record is complete.</p></div><div className="hero-actions"><span className="environment-badge"><span className="status-dot status-dot-good" />Tenant-scoped</span></div></section>{error && <div className="inline-alert"><strong>Alert action failed</strong><span>{error}</span><button className="text-button" type="button" onClick={() => void load()}>Retry</button></div>}<section className="metric-grid metric-grid-four"><article className="metric-card metric-card-accent"><span>Loaded alerts</span><strong>{alerts.length}</strong><small>{filter === "all" ? "All statuses" : `${filter} status`}</small></article><article className="metric-card metric-card-danger"><span>High priority</span><strong>{critical}</strong><small>High or critical in view</small></article><article className="metric-card"><span>Review model</span><strong>3</strong><small>Observe · investigate · resolve</small></article><article className="metric-card"><span>Evidence path</span><strong>→</strong><small>Open related event records</small></article></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">ALERT QUEUE</p><h2>{loading ? "Loading alert records" : `${alerts.length} alert${alerts.length === 1 ? "" : "s"}`}</h2></div><div className="filter-tabs" role="tablist" aria-label="Alert status filter">{["active", "resolved", "all"].map((item) => <button key={item} className={filter === item ? "filter-tab filter-tab-active" : "filter-tab"} type="button" onClick={() => setFilter(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div></div>{loading ? <div className="empty-state"><span className="loading-bar" />Loading alerts…</div> : alerts.length ? <div className="alert-list">{alerts.map((alert) => <article className="alert-row" key={alert.id}><span className={`severity-dot severity-${String(alert.severity || "medium").toLowerCase()}`} /><div className="alert-main"><div className="alert-title-row"><b>{alert.message}</b><span className={`decision-badge ${/critical|high/i.test(alert.severity) ? "badge-danger" : "badge-warning"}`}>{alert.severity}</span></div><small>{alert.source || "System"} · {formatDate(alert.created_at)} · {alert.status}</small><code>{alert.id}</code></div><button className="secondary-button alert-action" type="button" disabled={alert.status === "resolved" || resolving === alert.id} onClick={() => void resolve(alert.id)}>{alert.status === "resolved" ? "Resolved" : resolving === alert.id ? "Resolving…" : "Resolve"}</button></article>)}</div> : <div className="empty-state"><strong>No {filter === "all" ? "alert" : filter} records</strong><span>The control plane will show alerts here when they are recorded for this workspace.</span></div>}</section></div>;
}
